server:
  port: 8080

spring:
  datasource:
    username: root
    password: Djx980831
    url: jdbc:mysql://localhost:3306/scholarship?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

mconfig:
  swagger-ui-open: true